dcos: add simulate JVM application faults.md
chaos-mesh/website pull request #101
Opened 2021-07-28 09:41 UTC by Liuxiaozhen12

Signed-off-by: Liuxiaozhen12 <82579298+Liuxiaozhen12@users.noreply.github.com>
This PR is translated from https://github.com/chaos-mesh/website-zh/pull/32.

2021-07-28 09:42 UTC, Liuxiaozhen12 commented
/cc @qiancai @STRRL

2021-07-29 02:06 UTC, STRRL requested changes
Thanks @Liuxiaozhen12! PTAL! :D

2021-07-29 02:06 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +| oom    | Out of memory, supporting oom of piles, stacks, metaspace areas |
```suggestion
| oom    | Out of memory, supporting oom of heap, stack, metaspace |
```

JVM 里的堆内存特指 “heap memory”(算是专有名词？), 后面的两个也是, 应该直接放到那里就可以了吧。

2021-07-29 02:06 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +| cpf    | Connect pool full                                               |
```suggestion
| cpf    | Connection pool full                                               |
```
连接池 “connection pool”, 应该也是个专有名词

2021-07-29 02:06 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +| tde    | The first exception in a throw method                           |
```suggestion
| tde    | Throw the first exception of method declare                          |
```

2021-07-29 02:06 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +For the parameters passed to `chaosblade-exec-jvm`, Chaos Mesh will merge all fields in `flags` and `matchers` as a request body and then send it to `chaosblade-exec-jvm`. For details, refer to [chao
```suggestion
For the parameters passed to `chaosblade-exec-jvm`, Chaos Mesh will merge all fields in `flags` and `matchers` as a request body and then send it to `chaosblade-exec-jvm`. For details, refer to [chaosblade-exec-jvm/Protocol](https://github.com/chaosblade-io/chaosblade-dev-doc/blob/a7074ab656de469f7dfaa19227723d0967c590ae/zh-cn/chaosblade-exec-jvm/%E5%8D%8F%E8%AE%AE%E7%AF%87.md).
```

2021-07-29 04:00 UTC, Liuxiaozhen12 commented on docs/simulate-jvm-application-chaos.md
> +| return | Writes groovy and Java implement scenarios                      |
This problem has been solved here: https://github.com/chaos-mesh/website/pull/101/commits/3ca3824612e72e44e80b865ad3de60ca3e5cf73b. Shall I fix it in the Chinese document?

2021-07-29 04:01 UTC, Liuxiaozhen12 commented
@STRRL Thanks for your detailed review! PTAL again~

2021-07-30 04:00 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +| return | Writes groovy and Java implement scenarios                      |
I have fixed that in https://github.com/chaos-mesh/website-zh/pull/58. :D

2021-07-30 04:03 UTC, STRRL reviewed
rest LGTM!

2021-07-30 04:03 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +[jvm-chaos-demo](https://github.com/chaos-mesh/jvm-chaos-demo) is a simple Spring Boot application and here serves as a target application. A tested application is defined in `example/jvm/app.yaml` a
```suggestion
### 2. Create target applications

[jvm-chaos-demo](https://github.com/chaos-mesh/jvm-chaos-demo) is a simple Spring Boot application and here serves as a target application. A target application is defined in `example/jvm/app.yaml` as follows:
```

2021-07-30 04:52 UTC, STRRL approved these changes

2021-07-30 07:44 UTC, cwen0 commented
/merge

2021-07-30 07:47 UTC, merged