docs: add a document for HTTP faults
chaos-mesh/website pull request #103
Opened 2021-07-29 08:29 UTC by en-jin19

Signed-off-by: en-jin19 <jinenwei@pingcap.com>

In this PR, I have added a document for HTTP faults.

This PR is translated from: https://github.com/chaos-mesh/website-zh/pull/50/files.

2021-07-29 08:43 UTC, en-jin19 commented on docs/simulate-http-chaos-on-kubernetes.md
> +HTTPChaos supports combinations of different fault types.  If you have configured multiple HTTP fault types at the same time when creating HTTPChaos experiments, the order set to inject the faults wh
麻烦可以请帮忙看下最后一句 （When the `abort` fault cause short circuits, the connection will be directly interrupted.）是否表达好原文的意思吗？ 

该句的原文是：其中 <code>abort</code> 故障会导致短路，直接中断此次连接。@Hexilee

2021-07-29 08:43 UTC, en-jin19 commented on docs/simulate-http-chaos-on-kubernetes.md
> +| patch.queries`   | [][]string        | Specifies the attached key pair of the URI query with additional faults. |               | no       | - [foo, bar] |
请问这里的附加故障指的是注入的故障吗? @Hexilee

2021-07-30 00:38 UTC, Hexilee commented on docs/simulate-http-chaos-on-kubernetes.md
> +| patch.queries`   | [][]string        | Specifies the attached key pair of the URI query with additional faults. |               | no       | - [foo, bar] |
“附加故障” 是文档里的专有名词，指 `patch` 类的故障。

2021-07-30 00:39 UTC, Hexilee commented on docs/simulate-http-chaos-on-kubernetes.md
> +HTTPChaos supports combinations of different fault types.  If you have configured multiple HTTP fault types at the same time when creating HTTPChaos experiments, the order set to inject the faults wh
我觉得表达没问题。

2021-07-30 00:48 UTC, Hexilee requested changes
Rest LGTM

2021-07-30 00:48 UTC, Hexilee commented on docs/simulate-http-chaos-on-kubernetes.md
> +- `Patch`：adds additional content to HTTP request or response messages.
```suggestion
- `patch`：adds additional content to HTTP request or response messages.
```

2021-07-30 00:48 UTC, Hexilee commented on docs/simulate-http-chaos-on-kubernetes.md
> +- For HTTPChaos injection to take effect, try to avoid reusing TCP socket client. This is because HTTPChaos does not affect the HTTP requests that are sent via TCP socket before the fault injection.
```suggestion
- For HTTPChaos injection to take effect, the client should avoid reusing TCP socket. This is because HTTPChaos does not affect the HTTP requests that are sent via TCP socket before the fault injection.
```

2021-07-30 00:48 UTC, Hexilee commented on docs/simulate-http-chaos-on-kubernetes.md
> +</tbody> </table>
这通用字段部分是还没翻完吗。

2021-07-30 12:01 UTC, en-jin19 commented on docs/simulate-http-chaos-on-kubernetes.md
> +</tbody> </table>
@Hexilee 前期导出翻译文件时可能出了错误，对应部分已添加，麻烦请帮忙确认下，谢谢！

2021-07-30 17:22 UTC, en-jin19 commented on docs/simulate-http-chaos-on-kubernetes.md
> +Common fields are meaningful when the `target` of fault injuection is `Request` or `Response`.
在上次文件中，该部分由于导出翻译文件时出现错误而省略掉了，目前已补充上了对应内容，麻烦请帮忙看一下，谢谢~ @Hexilee

2021-07-30 17:39 UTC, en-jin19 commented
I have revised the translations according to the review, please kindly take a look, thanks! @Hexilee

2021-08-02 05:37 UTC, Hexilee requested changes
Rest LGTM

2021-08-02 05:37 UTC, Hexilee commented on docs/simulate-http-chaos-on-kubernetes.md
> +### `Request`-related fields
Should this be a 4-level title?

2021-08-02 06:14 UTC, en-jin19 commented on docs/simulate-http-chaos-on-kubernetes.md
> +### `Request`-related fields
原文中是都统一设置为了三级标题，不过英文中我改为四级标题吧 @Hexilee

2021-08-02 06:32 UTC, Hexilee approved these changes
LGTM

2021-08-02 06:33 UTC, cwen0 commented
/merge

2021-08-02 06:35 UTC, merged