docs: add a document "integrate Chaos Mesh to GitHub Actions"
chaos-mesh/website pull request #119
Opened 2021-08-09 06:25 UTC by en-jin19

Signed-off-by: en-jin19 <jinenwei@pingcap.com>

This PR is translated from #[41](https://github.com/chaos-mesh/website-zh/pull/41) and [#65](https://github.com/chaos-mesh/website-zh/pull/65).

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +Workflow is essentially a sequentially automated job configuration.  Note that the following job is configured in a single file.  In order to provide a clear explanation, we split the script into dif
```suggestion
In essence, a workflow is a sequentially automated job configuration.  Note that the following job is configured in a single file.  To provide a clear explanation, the script is split into different working groups:
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +- Set workflow name and trigger rules.
```suggestion
- Set the workflow name and the trigger rules.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  Name the workflow to "Chaos".  When you commit code or create a pull request to a master branch, this workflow will be triggered.
```suggestion
  Name the workflow to "Chaos". When you commit code or create a pull request to a master branch, this workflow is triggered.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +- Install CI related environment
```suggestion
- Install the CI-related environment.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  This configuration specifies Ubuntu operating system and creates a a kind cluster using helm/kind-action.  After that, it exports information about the cluster. Finally, it checks out the GitHub re
```suggestion
  This configuration specifies the operating system (Ubuntu) and creates a Kind cluster using helm/kind-action.  After that, it prints the cluster information. Finally, it checks out the GitHub repository that the workflow is to access.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +- Deploy an application
```suggestion
- Deploy an application.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  In the following example, this job deploys an application that will create two Kubernetes pods.
```suggestion
  In the following example, this job deploys an application that creates two Kubernetes Pods.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +- Inject faults using Chaos Mesh
```suggestion
- Inject faults using Chaos Mesh.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  With chaos-mesh-action, Chaos Mesh will be installed and inject faults automatically. The only things you need to do is to prepare the configuration of the chaos experiment and get its value encode
```suggestion
  Using chaos-mesh-action, Chaos Mesh is installed and injects faults automatically. You only need to prepare the configuration of the chaos experiment and get its value encoded in base64. If you want to inject network latency to the Pod, you can use the following configuration example:
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  Get the Base64 encoded value of the chaos experiment configuration file above using the command line below:
```suggestion
  Get the base64-encoded value of the chaos experiment configuration file above using the command below:
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  $ base64 chaos.yaml
```suggestion
  base64 chaos.yaml
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  Ping workflow from one pod to another pod in this job and observe network latency.
```suggestion
  In this job, the workflow sends ping requests from one Pod to another Pod and observes the network latency.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  Once a workflow is created, it can be triggered by creating a pull request to a master branch. Once the workflow completed its running process, the output of the job verification is similar to the
```suggestion
  Once a workflow is created, you can trigger it by creating a pull request to a master branch. Once the workflow completes its process, the output of the job verification is similar to the one below:
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  The output shows that there are a series of 10 milliseconds of delay, and each delay lasts for 5 seconds (refers to 5 times). This is in line with the configuration of chaos experiments that inject
```suggestion
  The output shows a series of 10-millisecond delays, and each delay lasts for 5 seconds (which is 5 times). This is consistent with the configuration of chaos experiments that are injected using chaos-mesh-action.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +Currently, chaos-mesh-action has been applied to [TiDB Operator](https://github.com/pingcap/tidb-operator). You can verify the restart of operator instances by injecting pod faults in the workflow. T
```suggestion
Currently, chaos-mesh-action has been applied in [TiDB Operator](https://github.com/pingcap/tidb-operator). By injecting Pod faults into the workflow, You can verify the restart of the Operator instances. This is to ensure that TiDB Operator can work properly when a Pod of TiDB operator is randomly deleted by the injected fault. For details, see the [TiDB Operator Workflow page](https://github.com/pingcap/tidb-operator/actions?query=workflow%3Achaos).
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +In the future, chaos-mesh-action will be applied to more tests for TiDB to ensure the stability of TiDB and its components. Welcome to use chaos-mesh-action to create your own workflow.
```suggestion
In the future, chaos-mesh-action will be applied in more TiDB tests to ensure the stability of TiDB and its components. You are welcome to use chaos-mesh-action to create your own workflow.
```

2021-08-09 12:36 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +If you find some errors in this document, or think some information is missing here, welcome to create an [issue](https://github.com/pingcap/chaos-mesh/issues) or a [pull request (PR)](https://github
```suggestion
If you find any issue in chaos-mesh-action, or find any information is missing, you are welcome to create an [GitHub issue](https://github.com/pingcap/chaos-mesh/issues) or a [pull request (PR)](https://github.com/chaos-mesh/chaos-mesh/pulls) in the Chaos Mesh repository. You can also join our slack channel [#project-chaos-mesh](https://slack.cncf.io/)  in the [CNCF](https://www.cncf.io/) workspace.
```

2021-08-09 16:20 UTC, en-jin19 commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  $ base64 chaos.yaml
should the original text also be revised? @TomShawn

2021-08-10 02:16 UTC, WangXiangUSTC commented
why write this document again, there is the English version https://chaos-mesh.org/blog/chaos-mesh-action-integrate-chaos-engineering-into-your-ci 😭

2021-08-10 02:43 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +This document describes how to integrate Chaos Mesh to custom the continuous integration (CI) using chaos-mesh-action. This helps you identify issues that have been introduced into system development
```suggestion
This document describes how to integrate Chaos Mesh to customize the continuous integration (CI) using chaos-mesh-action. This helps you identify issues that have been introduced into system development prior to product release.
```

2021-08-10 02:44 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +chaos-mesh-action is a GitHub action that have been released on [GitHub Marketplace](https://github.com/marketplace/actions/chaos-mesh). Its source code is on [GitHub](https://github.com/chaos-mesh/c
```suggestion
chaos-mesh-action is a GitHub action that has been released on [GitHub Marketplace](https://github.com/marketplace/actions/chaos-mesh). Its source code is on [GitHub](https://github.com/chaos-mesh/chaos-mesh-action) as well.
```

2021-08-10 02:46 UTC, TomShawn requested changes
Some of the comments are missed and there are still grammar issues. Please check again and ensure all comments are addressed.

2021-08-10 09:41 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  Using chaos-mesh-action, Chaos Mesh is be installed and injects faults automatically. You only need to prepare the configuration of the chaos experiment and get its value encoded in base64. If you
```suggestion
  Using chaos-mesh-action, Chaos Mesh is installed and injects faults automatically. You only need to prepare the configuration of the chaos experiment and get its value encoded in base64. If you want to inject network latency to the Pod, you can use the following configuration example:
```

2021-08-10 09:44 UTC, TomShawn commented on docs/integrate-chaos-mesh-into-github-actions.md
> +  In this job, the workflow sends ping requests from one Pod to another Pod and observes the network latency.
```suggestion
  In this job, the workflow sends ping requests from one Pod to another Pod. You can observe the network latency.
```

2021-08-10 09:50 UTC, TomShawn approved these changes
Rest LGTM
@WangXiangUSTC PTAL

2021-08-11 01:45 UTC, WangXiangUSTC approved these changes
LGTM

2021-08-11 03:10 UTC, TomShawn commented
@WangXiangUSTC Please help merge this PR. Thanks!

2021-08-11 08:17 UTC, WangXiangUSTC commented
@TomShawn the markdown links check failed, do we need to fix it?

2021-08-11 08:25 UTC, TomShawn commented
> @TomShawn the markdown links check failed, do we need to fix it?

Looks like it is unrelated to this PR. @g1eny0ung Would you help take a look? Thanks!

2021-08-11 08:53 UTC, merged