docs: add a doc "simulate GCP faults"
chaos-mesh/website pull request #120
Opened 2021-08-09 06:48 UTC by en-jin19

Signed-off-by: en-jin19 <jinenwei@pingcap.com>

This PR is translated from [#38](https://github.com/chaos-mesh/website-zh/pull/38) and [#64](https://github.com/chaos-mesh/website-zh/pull/64).

2021-08-10 13:15 UTC, fewdan requested changes

2021-08-10 13:15 UTC, fewdan commented on docs/simulate-gcp-chaos.md
> +- **Disk Loss**: uninstalls the storage volume from the specified EC2 instance.
change "ec2" to node ?

2021-08-11 08:40 UTC, en-jin19 commented on docs/simulate-gcp-chaos.md
> +- **Disk Loss**: uninstalls the storage volume from the specified EC2 instance.
I have revised the translation, please take a look, thanks!

2021-08-12 07:42 UTC, fewdan commented on docs/simulate-gcp-chaos.md
> +  For more information about reseting GCP instances, refer to [Resetting an GCP instance](https://cloud.google.com/compute/docs/instances/stop-start-instance#resetting_an_instance).
Maybe "For more information about reseting GCP instances" should be "For more information about resetting GCP instances" ?   

And "[Resetting an GCP instance]"  should be "[Resetting a GCP instance]" ?

2021-08-12 08:02 UTC, en-jin19 commented on docs/simulate-gcp-chaos.md
> +  For more information about reseting GCP instances, refer to [Resetting an GCP instance](https://cloud.google.com/compute/docs/instances/stop-start-instance#resetting_an_instance).
thanks, I have revised them, PTAL

2021-08-13 08:06 UTC, fewdan approved these changes
LGTM

2021-08-16 07:53 UTC, en-jin19 commented
/merge

2021-08-17 17:41 UTC, en-jin19 commented
/merge

2021-08-18 09:05 UTC, en-jin19 commented
/merge

2021-08-18 09:20 UTC, merged