chore: disable update temporally
chaos-mesh/website pull request #157
Opened 2021-11-02 10:18 UTC by g1eny0ung

Signed-off-by: Yue Yang <g1enyy0ung@gmail.com>

Related changes to https://github.com/chaos-mesh/chaos-mesh/pull/2446.

2021-11-03 07:20 UTC, STRRL approved these changes
LGTM!

2021-11-03 07:23 UTC, WangXiangUSTC approved these changes
LGTM

2021-11-03 21:00 UTC, en-jin19 commented on docs/run-a-chaos-experiment.md
> +The `Spec` field of Chaos Experiment is currently not allowed to be updated.
```suggestion
The `Spec` field of Chaos experiment is currently not allowed to be updated.
```

2021-11-03 21:02 UTC, en-jin19 commented on docs/run-a-chaos-experiment.md
> +For more details, see: <https://github.com/chaos-mesh/chaos-mesh/issues/2227>.
```suggestion
For more details, refer to the related [GitHub issue](https://github.com/chaos-mesh/chaos-mesh/issues/2227).
```

2021-11-03 21:03 UTC, en-jin19 commented on docs/run-a-chaos-experiment.md
> +The Dashboard doesn't support updating Chaos Experiments at this time because the `Spec` field of Chaos experiments is not allowed to be updated.
```suggestion
The Chaos Dashboard doesn't support updating Chaos experiments at this time, because the `Spec` field of Chaos experiments is not allowed to be updated.
```

2021-11-03 21:04 UTC, en-jin19 commented on docs/run-a-chaos-experiment.md
> +The `Spec` field of Chaos Experiment is currently not allowed to be updated.
```suggestion
The `Spec` field of Chaos experiment is currently not allowed to be updated.
```

2021-11-03 21:05 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/current/run-a-chaos-experiment.md
> +更多细节请参见：<https://github.com/chaos-mesh/chaos-mesh/issues/2227>。
```suggestion
更多细节，请参见对应的 [GitHub issue](https://github.com/chaos-mesh/chaos-mesh/issues/2227)。
```

2021-11-03 21:06 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/version-2.0.3/run-a-chaos-experiment.md
> +更多细节请参见：<https://github.com/chaos-mesh/chaos-mesh/issues/2227>。
```suggestion
更多细节，请参见对应的 [GitHub issue](https://github.com/chaos-mesh/chaos-mesh/issues/2227)。
```

2021-11-03 21:07 UTC, en-jin19 commented on versioned_docs/version-2.0.3/run-a-chaos-experiment.md
> +The `Spec` field of Chaos Experiment is currently not allowed to be updated.
```suggestion
The `Spec` field of Chaos experiment is currently not allowed to be updated.
```

2021-11-03 21:07 UTC, en-jin19 commented on versioned_docs/version-2.0.3/run-a-chaos-experiment.md
> +For more details, see: <https://github.com/chaos-mesh/chaos-mesh/issues/2227>.
```suggestion
For more details, refer to the related [GitHub issue](https://github.com/chaos-mesh/chaos-mesh/issues/2227).
```

2021-11-03 21:07 UTC, en-jin19 commented on versioned_docs/version-2.0.3/run-a-chaos-experiment.md
> +The Dashboard doesn't support updating Chaos Experiments at this time because the `Spec` field of Chaos experiments is not allowed to be updated.
```suggestion
The Chaos Dashboard doesn't support updating Chaos experiments at this time, because the `Spec` field of Chaos experiments is not allowed to be updated.
```

2021-11-03 21:09 UTC, en-jin19 requested changes
Rest LGTM

2021-11-04 03:12 UTC, g1eny0ung commented
@en-jin19 Already follow suggestions.

2021-11-04 08:17 UTC, en-jin19 approved these changes
LGTM

2021-11-05 07:47 UTC, WangXiangUSTC commented
/merge

2021-11-05 08:57 UTC, merged