docs: run e2e tests
chaos-mesh/website pull request #17
Opened 2020-11-24 09:20 UTC by STRRL

It's apart of https://github.com/chaos-mesh/chaos-mesh/issues/1187.

2020-11-27 09:43 UTC, fewdan requested changes

2020-11-27 09:43 UTC, fewdan commented on docs/development_guides/run_e2e_tests.md
> +It will takes about 20~30 minutes to finish all the test cases.
s/It will takes .../It will take ..../g

2020-11-27 09:43 UTC, fewdan commented on docs/development_guides/run_e2e_tests.md
> +Some of them are public docker image like `nginx:latest`, kubernetes will pull it from docker registry, so them could be ignored.
s/so them could be ignored./so they could be ignored./g

2020-11-27 09:43 UTC, fewdan commented on docs/development_guides/run_e2e_tests.md
> +If you just want run apart of test cases, or want run it on an existing cluster, that's a common requirements during developing e2e test or testing compatible between chaos-mesh and cloud-provided ku
a common requirement

2020-11-27 09:43 UTC, fewdan commented on docs/development_guides/run_e2e_tests.md
> +If you just want run apart of test cases, or want run it on an existing cluster, that's a common requirements during developing e2e test or testing compatible between chaos-mesh and cloud-provided ku
"If you just want run apart of test cases, or want run it on an existing cluster"
It should be changed to "want to run".

2020-11-28 08:06 UTC, Yiyiyimu commented
Hi @STRRL you could have a try for [Grammarly](https://www.grammarly.com/), which is a pretty good grammar check tool that could either be used as a chrome extension or in Microsoft office

2020-11-28 08:52 UTC, Yiyiyimu commented on docs/development_guides/run_e2e_tests.md
> +./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
Idk if it is just my case but my environment didn't set KUBECONFIG by default, so I need to run `export KUBECONFIG=$HOME/.kube/config` before the test

2020-11-28 14:15 UTC, STRRL commented
> Hi @STRRL First thx for the doc. It really helped me a lot! And for what fewdan ask for, you could have a try for [Grammarly](https://www.grammarly.com/), which is a pretty good grammar check tool that could either be used as a chrome extension or in Microsoft office

Thanks! I will take a try! :P

2020-11-28 14:28 UTC, STRRL commented on docs/development_guides/run_e2e_tests.md
> +./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
I will append usage for `KUBECONFIG` to switch their target kubernetes cluster. :D

But for your situation, that's wired, as these [codes](https://github.com/kubernetes/kubernetes/blob/5ed4b76a03b5eddc62939a1569b61532b4a06a72/staging/src/k8s.io/client-go/tools/clientcmd/loader.go#L145-L154) say, although KUBECONFIG not set, client still try to load config from `$HOME/.kube/config`

2020-11-28 14:34 UTC, Yiyiyimu commented on docs/development_guides/run_e2e_tests.md
> +./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
Yeah but [e2e_test.go](https://github.com/chaos-mesh/chaos-mesh/blob/master/test/e2e/e2e_test.go#L97-L100) explicitly check the value of environment variable `KUBECONFIG` ☹️ maybe we could remove this check

2020-11-28 14:47 UTC, STRRL commented on docs/development_guides/run_e2e_tests.md
> +./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
Oops, you are right, `KUBECONFIG` is required for kubernetes test framework.😅 

If we do not provide a `KUBECONFIG`, the test framework will just try in-cluster configuration.

2020-11-29 03:51 UTC, Yiyiyimu commented on docs/development_guides/run_e2e_tests.md
> +./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
Ah got it! Thanks~

2020-11-30 01:55 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +We build our e2e framework based on [kubetest2](https://github.com/kubernetes-sigs/kubetest2) and [ginkgo](https://onsi.github.io/ginkgo/). There are several ways to run e2e tests.
Why would anyone need this? Please explain what e2e is and in what scenarios would users need this?

2020-11-30 03:32 UTC, STRRL commented
PTAL, @Yiyiyimu @Yiyiyimu @fewdan

2020-11-30 07:17 UTC, YangKeao commented on docs/development_guides/run_e2e_tests.md
> +./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
Have you misses `--install-chaos-mesh`?

2020-11-30 14:47 UTC, Yiyiyimu commented
LGTM, but there is a problem for me on running e2e test locally. When I change something for chaos mesh, and redo the e2e test, I found the test result didn't change. Only if I set up a new kind cluster could I get the new test result. 
Don't know if it could be reproduced

---
**To Reproduce**
```shell
# After running the first e2e test and did some change
make && make docker-push
helm upgrade...
# Find `controller-manager` is replaced to the new one
make e2e-build # not necessary
./test/image/e2e/bin/ginkgo ./test/image/e2e/bin/e2e.test
# Nothing change
```

2020-11-30 15:41 UTC, STRRL commented
Hi @Yiyiyimu , `helm upgrade` did not change the image of the pod, it is still like  `pingcap/chaos-mesh:latest`. As `image` of a container doesn't change, kubernetes will not pull the "newer" images (by default). So you could manually update the container by:
- `helm upgrade chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set 'controllerManager.imagePullPolicy=Always'`
Or
- ssh to the node, manually execute "docker pull pingcap/chaos-mesh:latest", then `kubectl -n chaos-testing delete pod chaos-controller-manager-xxxx-xxx` to rebuild the pod.

2020-12-01 12:26 UTC, Yiyiyimu commented
That indeed is the problem! Thanks a lot @STRRL !!

2020-12-10 06:39 UTC, WangXiangUSTC commented
need to add it in sidebars.js

2020-12-11 05:29 UTC, STRRL commented
@WangXiangUSTC  fixed! PTAL

2020-12-15 15:58 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +You could run full e2e tests on your local machine, just execute `./hack/e2e.sh`. It only needs docker installed on your machine.
when would you want to run full e2e tests?

2020-12-15 16:00 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +If you just want to run apart of test cases, or want to run it on an existing cluster, that's a common requirement during developing e2e tests or testing compatible between chaos-mesh and cloud-provi
> If you just want to run apart of test cases"

Should this refer to the next part?

2020-12-17 07:02 UTC, STRRL commented on docs/development_guides/run_e2e_tests.md
> +You could run full e2e tests on your local machine, just execute `./hack/e2e.sh`. It only needs docker installed on your machine.
We usually do not execute full e2e tests on the local machine. 🙈 It just introduces a way to run full e2e tests.

2020-12-17 07:04 UTC, STRRL commented on docs/development_guides/run_e2e_tests.md
> +If you just want to run apart of test cases, or want to run it on an existing cluster, that's a common requirement during developing e2e tests or testing compatible between chaos-mesh and cloud-provi
Fixed.

2020-12-17 07:05 UTC, STRRL commented
Hi @dcalvin, PTAL 😁

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +We build our e2e framework based on [kubetest2](https://github.com/kubernetes-sigs/kubetest2) and [ginkgo](https://onsi.github.io/ginkgo/). There are several ways to run e2e tests.
```suggestion
To ensure the correctness of code contributions, we use  "endpoint to endpoint" (e2e) testing to test Chaos Mesh on a real Kubernetes cluster. This document walks you through how to run e2e tests for each code contribution that you make. 
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +You could run full e2e tests on your local machine, just execute `./hack/e2e.sh`. It only needs docker installed on your machine.
```suggestion
## Run e2e tests on your local-machine

You could run  full e2e tests on your local machine by executing `./hack/e2e.sh`. It requires docker to be installed locally.
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +It will take about 20~30 minutes to finish all the test cases.
```suggestion
It generally takes about 20~30 minutes to finish all the test cases. Therefore, we do not recommend this method.
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +If you want to run e2e tests on an existing cluster, that's a common requirement during developing e2e tests or testing compatible between chaos-mesh and cloud-provided kubernetes cluster.
```suggestion
For common requirements such as developing e2e test cases or testing compatibilities between Chaos Mesh and Kubernetes clusters on the cloud, you would normally need to run 22e tests on an existing cluster. Take the following steps:
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +It supposes that chaos-mesh is already installed on your cluster, you could follow this [document](https://chaos-mesh.org/docs/user_guides/installation) to install chaos-mesh.
```suggestion
**Note:** Please make sure that Chaos Mesh is already installed on your local.
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +Others are private or already changed with your changes, so you need manually preparing these images.
```suggestion
1. Get the required images as listed below

    - pingcap/e2e-helper:latest
    - nginx:latest
    ```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +Others are private or already changed with your changes, so you need manually preparing these images.
> Some of them are public docker images like `nginx:latest`, kubernetes will pull it from docker registry, so they could be ignored. Others are private or already changed with your changes, so you need manually preparing these images.

This kind of info is really confusing and redundant. Please consider removing them. Or you can provide links for the images

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +You could build e2e-helper docker images by
```suggestion
2. Build e2e-helper docker images by executing:
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +Then you should load this docker image to all nodes in the cluster. You could do this with
```suggestion
3. Load this docker image to all nodes in the cluster by executing:
:
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +After that, you could execute e2e tests by
```suggestion
4. Now you should be able to execute e2e tests by executing:
```

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +After that, you could execute e2e tests by
For this kind of instructions,  identify the operations and write them in a sequential manner (1. 2. 3. 4 ).  DONOT write it non-stopping with AND, THEN, AFTER THAT.

And DONOT use "you could/should" because it's a step they WILL DO, not something they choose to do.

2020-12-17 11:48 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +Our e2e tests are built on [ginkgo](https://onsi.github.io/ginkgo/), we could use `--focus` for running part of e2e tests.
When we should just run part of the e2e?

2020-12-18 03:13 UTC, STRRL commented
Thanks for your suggestions @dcalvin! 

I accept your changes and append when we need to run part of e2e tests. PTAL.

2020-12-18 03:14 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +After you write new e2e test cases, or make changes on certain module, you do not need run full e2e tests. Our e2e tests are built on [ginkgo](https://onsi.github.io/ginkgo/), we could use `--focus`
```suggestion
After you write new e2e test cases or make changes on a certain module, you do not need to run full e2e tests. Our e2e tests are built on [ginkgo](https://onsi.github.io/ginkgo/), so you can use `--focus` for running part of e2e tests. 
```

2020-12-18 03:16 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +All e2e test cases are described like:
```suggestion
For example, we have our full e2e tests described as below:
```

2020-12-18 03:17 UTC, dcalvin commented on docs/development_guides/run_e2e_tests.md
> +We could use `./test/image/e2e/bin/ginkgo -focus="NetworkPartition" ./test/image/e2e/bin/e2e.test` for only running "NetworkPartition" e2e test case.
```suggestion
You can use `./test/image/e2e/bin/ginkgo -focus="NetworkPartition" ./test/image/e2e/bin/e2e.test` to run only the "NetworkPartition" e2e test case.
```

2020-12-21 08:19 UTC, STRRL commented
Hi @dcalvin, PTAL 😁

2021-01-07 03:20 UTC, WangXiangUSTC commented
https://github.com/chaos-mesh/chaos-mesh/pull/1300
this pr update the Makefile, and some commands can't execute success(for example: make image-e2e-helper). This pr needs to do some update. 😿

2021-04-07 03:23 UTC, STRRL commented
As the build of e2e has changed so much, I think this PR should be closed.

I will write another doc for website-cn at first.

2021-04-07 03:23 UTC, closed without merging