docs: about create serial and parallel node on dashboard
chaos-mesh/website pull request #191
Opened 2021-12-09 08:24 UTC by STRRL

Signed-off-by: STRRL <str_ruiling@outlook.com>

2021-12-13 04:10 UTC, g1eny0ung approved these changes
LGTM. And some conflicts need to be resolved

2021-12-13 22:12 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/current/run-chaos-experiments-in-serial-or-parallel.md
> +### 嵌套串行与并行节点
```suggestion
### 创建串行节点

Chaos Dashboard 会创建一个预定义的串行节点，名为 `entry`。因此，当在 Chaos Dashboard 中创建串行节点的 Workflow 时，默认会在 `entry` 下创建流程。

![Create Serial Node On Dashboard](./img/create-serial-node-on-dashboard.png)

### 创建并行节点

你可以在 Chaos Dashboard 中创建一个并行节点 `Parallel`，然后在该节点下创建子节点。

![Create Parallel Node on Dashboard](./img/create-parallel-node-on-dashboard.png)

### 嵌套串行节点与并行节点
```

2021-12-13 22:13 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/version-2.1.1/run-chaos-experiments-in-serial-or-parallel.md
> +### 嵌套串行与并行节点
```suggestion
### 创建串行节点

Chaos Dashboard 会创建一个预定义的串行节点，名为 `entry`。因此，当在 Chaos Dashboard 中创建串行节点的 Workflow 时，默认会在 `entry` 下创建流程。

![Create Serial Node On Dashboard](./img/create-serial-node-on-dashboard.png)

### 创建并行节点

你可以在 Chaos Dashboard 中创建一个并行节点 `Parallel`，然后在该节点下创建子节点。

![Create Parallel Node on Dashboard](./img/create-parallel-node-on-dashboard.png)

### 嵌套串行节点与并行节点
```

2021-12-13 22:18 UTC, en-jin19 commented on docs/run-chaos-experiments-in-serial-or-parallel.md
> +
```suggestion
### 创建并行节点

你可以在 Chaos Dashboard 中创建一个并行节点 `Parallel`，然后在该节点下创建子节点。

![Create Parallel Node on Dashboard](./img/create-parallel-node-on-dashboard.png)

### 嵌套串行节点与并行节点

### Create serial nodes

Chaos Dashboard creates a predefined serial node called `entry`. Therefore, when creating Workflow with serial nodes using Chaos Dashboard, the Workflow is created under `entry` by default.

![Create Serial Node On Dashboard](./img/create-serial-node-on-dashboard.png)

### Create parallel nodes

You can create a parallel node `Parallel` and create sub-nodes under `Parallel`.

![Create Parallel Node on Dashboard](./img/create-parallel-node-on-dashboard.png)

### Nest serial and parallel nodes

You can create more complex processes by nesting serial and parallel nodes together.

```

2021-12-13 22:19 UTC, en-jin19 commented on versioned_docs/version-2.1.1/run-chaos-experiments-in-serial-or-parallel.md
> +You could also combine any serial and parallel as you want.
```suggestion
## Create Workflow with Serial or Parallel nodes using Chaos Dashboard

### Create serial nodes

Chaos Dashboard creates a predefined serial node called `entry`. Therefore, when creating Workflow with serial nodes using Chaos Dashboard, the Workflow is created under `entry` by default.

![Create Serial Node On Dashboard](./img/create-serial-node-on-dashboard.png)

### Create parallel nodes

You can create a parallel node `Parallel` and create sub-nodes under `Parallel`.

![Create Parallel Node on Dashboard](./img/create-parallel-node-on-dashboard.png)

### Nest serial and parallel nodes

You can create more complex processes by nesting serial and parallel nodes together.
```

2021-12-13 22:20 UTC, en-jin19 requested changes
I have language reviewed the docs, please take a look, thanks!

2021-12-13 22:22 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/current/run-chaos-experiments-in-serial-or-parallel.md
> +## 在 Chaos Dashboard 中创建串行或并行节点的 Workflow
```suggestion
## 通过 Chaos Dashboard 创建串行或并行节点的 Workflow
```

2021-12-13 22:23 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/version-2.1.1/run-chaos-experiments-in-serial-or-parallel.md
> +## 在 Chaos Dashboard 中创建串行或并行节点的 Workflow
```suggestion
## 通过 Chaos Dashboard 创建串行或并行节点的 Workflow
```

2021-12-13 22:29 UTC, en-jin19 commented on docs/run-chaos-experiments-in-serial-or-parallel.md
> +## Create Workflow with Serial or Parallel nodes using Chaos Dashboard
```suggestion
## Create a workflow with serial or parallel nodes using Chaos Dashboard
```

2021-12-15 03:58 UTC, STRRL commented
Updated! PTAL

@en-jin19

2021-12-15 07:49 UTC, en-jin19 approved these changes
LGTM

2021-12-16 03:27 UTC, cwen0 commented
/merge

2021-12-16 03:28 UTC, merged