doc: add note for use install.sh
chaos-mesh/website pull request #22
Opened 2020-12-07 06:31 UTC by WangXiangUSTC

Signed-off-by: xiang <xiang13225080@163.com>

2020-12-07 12:58 UTC, dcalvin requested changes
Please update in all related versions.

2020-12-07 12:58 UTC, dcalvin commented on docs/user_guides/installation.md
> +> `install.sh` is suitable for trying out the chaos Mesh. Helm is recommended for installation if Chaos Mesh is used in a production environment or if you want to use it deeply.
```suggestion
> `install.sh` is suitable for trying Chaos Mesh out. If you want to use Chaos Mesh in production or other serious scenarios, Helm is the recommended deployment method.

2020-12-07 12:58 UTC, dcalvin commented on docs/user_guides/installation.md
> +> `install.sh` is suitable for trying out the chaos Mesh. Helm is recommended for installation if Chaos Mesh is used in a production environment or if you want to use it deeply.
No "the" before Chaos Mesh, which is a proper noun.

2020-12-07 12:58 UTC, dcalvin commented on docs/user_guides/installation.md
>  Verify if the chaos mesh is running (For the use of _kubectl_, you can refer to the [documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands).)
```suggestion
Verify if Chaos Mesh is running (For the use of _kubectl_, you can refer to the [documentation](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands).)
```

2020-12-08 03:42 UTC, WangXiangUSTC commented
@dcalvin all comment addressed, PTAL again

2020-12-08 03:43 UTC, dcalvin approved these changes
LGTM

2020-12-08 10:09 UTC, merged