chore: update some information about CPU StressChaos
chaos-mesh/website pull request #235
Opened 2022-01-25 08:12 UTC by FingerLeader

Signed-off-by: FingerLeader <wanxfinger@gmail.com>

2022-01-25 08:57 UTC, en-jin19 commented
@FingerLeader Could you please invite a tech reviewer for this PR?

Besides, please update the same English docs of v2.1.2 and v2.0.6 and Chinese docs of the current version,  v2.1.2, and v2.0.6? thanks!

2022-01-25 09:42 UTC, FingerLeader commented
> @FingerLeader Could you please invite a tech reviewer for this PR?
> 
> Besides, please update the same English docs of v2.1.2 and v2.0.6 and Chinese docs of the current version, v2.1.2, and v2.0.6? thanks!

Thank you for reminding, I have updated other docs, and PTAL /cc @STRRL

2022-01-26 07:12 UTC, en-jin19 approved these changes
LGTM

2022-01-27 07:58 UTC, STRRL requested changes
It seems https://github.com/chaos-mesh/chaos-mesh/pull/2623 has not been cherry-picked into release-2.0 and release-2.1, so changes on versioned documentation are NOT required.

And it's better to introduce why we use `memStress` instead of `stress-ng`, what's the different behavior between them.

2022-01-27 07:58 UTC, STRRL commented on docs/simulate-heavy-stress-on-kubernetes.md
> +| workers   | int    | Specifies the number of threads that apply CPU stress |               | Yes      | `1`     |
I do not think this description for `MemoryStressor.workers` is correct. :thinking:

2022-01-27 07:58 UTC, STRRL commented on docs/simulate-heavy-stress-on-kubernetes.md
>  | size      | string | Specifies the maximum memory size available for total    |               | No       | `256MB` |
Please explain that `size` is the expected allocated memory for **each worker**, and the final sum of allocated memory size is `workers * size`.

And please also introduce that we could use percentage `%` in here.

2022-01-27 16:36 UTC, FingerLeader commented on docs/simulate-heavy-stress-on-kubernetes.md
> +| workers   | int    | Specifies the number of threads that apply CPU stress |               | Yes      | `1`     |
This PR is not for [chaos-mesh/chaos-mesh#2623](https://github.com/chaos-mesh/chaos-mesh/pull/2623), just fix some typo for the origin implementation of StressChaos. I will add details for #2623 in another PR.

2022-01-28 08:44 UTC, FingerLeader commented
I have update docs of stressChaos in another PR, both for new changes and old typo. This PR can be closed.

2022-01-28 08:44 UTC, closed without merging