doc: add document for dashboard
chaos-mesh/website pull request #24
Opened 2020-12-08 10:00 UTC by WangXiangUSTC

2020-12-08 10:04 UTC, g1eny0ung requested changes

2020-12-08 10:04 UTC, g1eny0ung commented on docs/user_guides/dashboard.md
> +id: Dashboard
`Dashboard` => `dashboard`.

2020-12-08 10:20 UTC, g1eny0ung approved these changes

2020-12-17 11:04 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Click the button `NEW EXPERIMENT` to create a new chaos experiment:
```suggestion
To create a chaos experiment on Chaos Dashboard:

1. Click the **NEW EXPERIMENT** button to create a new chaos experiment:
```

2020-12-17 11:04 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Then you need to configure the chaos experiment, including the experiment name, type, scheduling information, etc:
```suggestion
2. Configure the chaos experiment, including the experiment name, type, scheduling information, etc.
```

2020-12-17 11:04 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +### Manage Chaos Experiment
```suggestion
## Manage a chaos experiment
```

2020-12-17 11:04 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Click the button `Experiments` to view all the chaos experiments:
```suggestion
To manage a specific chaos experiment:

 1. Click the **Experiments** button to view all the chaos experiments.
```

2020-12-17 11:04 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +You can choose an experiment to view the details, and pause, archive, or update the chaos experiment on the page:
```suggestion
2. Choose the target experiment to view the details, pause, archive, or update.
```

2020-12-17 11:04 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Click the button `NEW EXPERIMENT` to create a new chaos experiment:
Button names should be bold.

2020-12-17 11:05 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Chaos Dashboard is a Web UI for managing, designing, monitoring Chaos Experiments. Stay tuned for more supports or join us in making it happen.
This is a user doc, not a blog article - so no call to action.

2020-12-17 12:20 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +Dashboard supports the `security mode`, which required to login with a token. The token is generated by Kubernetes, and the user can only perform things within the scope of the token authority on the
it means `the token's corresponding authority`

2020-12-17 12:20 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +> 2. The security mode is disabled if you install Chaos Mesh by `install.sh`, which is suitable for trying Chaos Mesh out.
Non-test scenarios

2020-12-17 12:21 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +If the Dashboard is installed with security mode, you need to fill in `Name` and `Token` when you open Dashboard in the browser. Otherwise, you can skip this section.
Only when using helm to install Chaos Mesh, the security mode is enabled by default. When use install.sh, the security mode is disabled

2020-12-17 12:23 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +Then create `ServiceAccount`, and bind the `ServiceAccount` with `Role`. Refer to [RBAC](https://kubernetes.io/zh/docs/reference/access-authn-authz/rbac/) for more details.
don't found `1`

2020-12-17 12:25 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> + The `Name` can be any string used to identify the `Token`, and a meaningful `Name` is suggested, such as `Cluster-Manager`, to indicate that the `Token` has permissions managed chaos experiments in
it is the name of the token, users can name it as will

2020-12-17 12:40 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +Then create `ServiceAccount`, and bind the `ServiceAccount` with `Role`. Refer to [RBAC](https://kubernetes.io/zh/docs/reference/access-authn-authz/rbac/) for more details.
oh, get it

2020-12-17 12:43 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +
done

2020-12-17 12:51 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +Get the token of `ServiceAccount` created above, refer to [getting-a-bearer-token](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md#getting-a-beare
I add an example command

2020-12-17 13:02 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Dashboard supports the `security mode`, which required to login with a token. The token is generated by Kubernetes, and the user can only perform things within the scope of the token authority on the
where do you define the corresponding authority?

2020-12-17 13:06 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +If the Dashboard is installed with security mode, you need to fill in `Name` and `Token` when you open Dashboard in the browser. Otherwise, you can skip this section.
Please modify it directly

2020-12-17 13:10 UTC, dcalvin commented on docs/user_guides/dashboard.md
> + The `Name` can be any string used to identify the `Token`, and a meaningful `Name` is suggested, such as `Cluster-Manager`, to indicate that the `Token` has permissions managed chaos experiments in
This would be confusing - you refer it as "The Name" but it has not been introduced earlier. Maybe you could say something like: 

Now you have the token generated, you need to identify it with a `Name`. A meaningful name is suggested, for example, `Cluster-Manager`, to indicate that the `Token` has permissions managed chaos experiments in the cluster.

2020-12-17 13:11 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +### Sign in
Is this the step to sign in? But I see in the description you just name the token. There is no sign in operation indicated.

2020-12-18 02:56 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +Dashboard supports the `security mode`, which required to login with a token. The token is generated by Kubernetes, and the user can only perform things within the scope of the token authority on the
1. it's the `role`, define the authority
2. then create a `service-account`, bind it with a `role`
3. get the token of the `service-account`

2020-12-18 02:58 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +### Security Mode
update to `Enable/Disable security mode`

2020-12-18 03:03 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Dashboard supports the `security mode`, which required to login with a token. The token is generated by Kubernetes, and the user can only perform things within the scope of the token authority on the
I updated the text.

2020-12-18 03:09 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +> 2. The security mode is disabled if you install Chaos Mesh by `install.sh`, which is suitable for trying Chaos Mesh out.
```suggestion
> 1. For actual testing scenarios, we strongly recommend that you enable the security mode.
> 2. The security mode is disabled if you install Chaos Mesh by `install.sh`, which is suitable for trying Chaos Mesh out.
```

2020-12-18 03:13 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> + The `Name` can be any string used to identify the `Token`, and a meaningful `Name` is suggested, such as `Cluster-Manager`, to indicate that the `Token` has permissions managed chaos experiments in
update in 4a1533d

2020-12-18 03:13 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +If the Dashboard is installed with security mode, you need to fill in `Name` and `Token` when you open Dashboard in the browser. Otherwise, you can skip this section.
update in 4a1533d

2020-12-18 03:16 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +### Sign in
Yes, there is a picture below, it shows the sign in  InputBox

2020-12-18 03:43 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +### Sign in
I think we'd better indicate also in the description.

2020-12-18 03:58 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +### Sign in
add a description in b5aac41

2020-12-21 08:26 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +- Cluster Manager
```suggestion
    - Cluster Manager
```
Please adjust the indent. It should not be at the same level as the sentence above.

2020-12-21 08:44 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +- Cluster Manager
all the four roles are update

2020-12-21 09:50 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +Now you have the token generated, you need to identify it with a `Name`. A meaningful name is suggested, for example, `Cluster-Manager`, to indicate that the token has permissions managed chaos exper
```suggestion
With the token generated, you need to identify it with a `Name`. A meaningful name is recommended, for example, `Cluster-Manager`, to indicate that the token has permissions managed chaos experiments in the cluster.
```

2020-12-21 09:51 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +title: Dashboard
Where would you put this document?

2020-12-21 10:25 UTC, WangXiangUSTC commented on docs/user_guides/dashboard.md
> +title: Dashboard
under `User Guides`

2020-12-21 13:23 UTC, dcalvin approved these changes
LGTM

2020-12-21 13:24 UTC, dcalvin commented on docs/user_guides/dashboard.md
> +> 2. The security mode is disabled if you install Chaos Mesh by `install.sh`, which is suitable for trying Chaos Mesh out.
These should be bullet items

2020-12-22 01:54 UTC, merged