chore: update screenshot for choose-task-type
chaos-mesh/website pull request #258
Opened 2022-03-01 09:24 UTC by STRRL

Signed-off-by: STRRL <str_ruiling@outlook.com>

2022-03-02 05:51 UTC, g1eny0ung requested changes

2022-03-04 06:24 UTC, en-jin19 commented on i18n/zh/docusaurus-plugin-content-docs/current/create-chaos-mesh-workflow.md
> +   ![Choose Task Type](./img/choose-task-type.png)
```suggestion
    ![Choose Task Type](./img/choose-task-type.png)
```

2022-03-04 06:40 UTC, en-jin19 approved these changes
LGTM

2022-03-04 06:45 UTC, g1eny0ung commented on i18n/zh/docusaurus-plugin-content-docs/current/create-chaos-mesh-workflow.md
> +   ![Choose Task Type](./img/choose-task-type.png)
I take another look and found that there have no more problems. 🤔 I will now merge this PR.

2022-03-04 06:45 UTC, g1eny0ung approved these changes

2022-03-04 06:46 UTC, merged