delete: overlapping paragraph and fix summary
chaos-mesh/website pull request #40
Opened 2021-02-03 02:56 UTC by milasuperstar

Signed-off-by: Mila Wu <wuzaixuan@pingcap.com>

2021-02-03 02:59 UTC, milasuperstar commented
PTAL @dcalvin

2021-02-05 06:33 UTC, g1eny0ung requested changes

2021-02-05 06:33 UTC, g1eny0ung commented on blog/2020-11-26-how-a-top-game-company-uses-chaos-engineering-to-improve-testing.md
> +summary: NetEase Fuxi AI Lab is China’s first professional game AI research institution. In their search for a Chaos Engineering tool to test their Kubernetes-based AI training platform, they chose C
Refer to https://v2.docusaurus.io/docs/markdown-features#markdown-headers.  Seems you need the `description` field.

2021-02-05 06:33 UTC, g1eny0ung commented on blog/2020-11-26-how-a-top-game-company-uses-chaos-engineering-to-improve-testing.md
> -<!--truncate-->
The `<!--truncate-->` and its above content represents a brief description of the blog. These should be preserved.

2021-02-05 06:35 UTC, g1eny0ung commented on blog/2020-11-26-how-a-top-game-company-uses-chaos-engineering-to-improve-testing.md
> -<!--truncate-->
https://v2.docusaurus.io/docs/blog#summary-truncation

2021-02-05 07:28 UTC, g1eny0ung approved these changes
LGTM

2021-02-05 07:28 UTC, merged